[tasks.juliafmt]
command = "julia"
args = ["-e", "using JuliaFormatter; format(pwd(), indent=2);"]

[tasks.nice]
dependencies = ["juliafmt"]

[tasks.lemon]
command = "julia"
args = ["--project=.", "produce_lemon_netgen_input_spec.jl", "${@}"]
